#!/bin/sh
#export EPICS_CA_SERVER_PORT=6064
#export EPICS_CA_REPEATER_PORT=6065
export EDMDATAFILES=../mks937aApp/opi/edl:../mks937aApp/opi/symbol:.
#edm -x -m "device=TS-VAC-PENG-01" mks937a-peng.edl &
edm -x -eolc mks937a-launch.edl &
