# Makefile.Host
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#DBDINSTALL +=  psc.dbd
#DBDINSTALL += $(EPICS_BASE)/dbd/dbCommon.dbd
#DBDINSTALL += $(GENSUB)/dbd/genSubRecord.dbd

include $(TOP)/config/RULES.Host
#----------------------------------------
#  ADD RULES AFTER THIS LINE
